import type { Metadata } from 'next';
// import { Changa } from 'next/font/google';
import './globals.css';
import { SiteHeader } from '@/components/site-header';
import { SidebarProvider } from '@/components/ui/sidebar';
import { ThemeProvider } from '@/components/theme-provider';

// const changa = Changa({
//   weight: ['200', '300', '400', '500', '600', '700', '800'],
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-changa',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased min-h-screen">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <SidebarProvider className="flex flex-col">
            <SiteHeader />
            {children}
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
